Revert "[Fuchsia] Build Fuchsia runtime on ToT bots"
This reverts commit 7310c3e0dbe45e349da30a02bd84f1f02ed7b052.

Reason for revert: This is breaking the branching process with:
KeyError: "checkout_fuchsia was used as a variable, but was not declared in the vars dict (file '.../src/DEPS', line 3676)"

Original change's description:
> [Fuchsia] Build Fuchsia runtime on ToT bots
>
> Allow ToT builders to build Fuchsia runtime.
> Unbreaks Fuchsia clang builders.
>
> Bug: 1041149
> Change-Id: I6ca56a48ae6a9d926eb63fd2bd993e39db2d76ce
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2770190
> Auto-Submit: Chong Gu <chonggu@google.com>
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Commit-Queue: Nico Weber <thakis@chromium.org>
> Commit-Queue: Chong Gu <chonggu@google.com>
> Cr-Commit-Position: refs/heads/master@{#864398}

Bug: 1041149,1189983
Change-Id: I2fffee0e204965dc5d5620b1c608a092ed481886
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2773730
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Michael Moss <mmoss@chromium.org>
Auto-Submit: Michael Moss <mmoss@chromium.org>
Commit-Queue: Michael Moss <mmoss@chromium.org>
Cr-Commit-Position: refs/heads/master@{#864576}
GitOrigin-RevId: 822859e43d828215e094c2f002d37ae84b604d9f