Revert of Make sure no stale LLD checkout is around. (patchset #1 id:1 of https://codereview.chromium.org/2220113002/ )
Reason for revert:
Breaks clang_upload bot:

OSError: [Errno 2] No such file or directory: '/b/build/slave/linux_upload_clang/build/src/third_party/llvm/tools/lld'

It seems that RmTree requires the directory to exist.

Original issue's description:
> Make sure no stale LLD checkout is around.
>
> We checked out LLD for a while on all platforms, and now some bots
> have stale checkouts of it.  See bug for details.
>
> BUG=635108
>
> Committed: https://crrev.com/f2e30b8c230d923e61752352cf4c37eb13eea3d2
> Cr-Commit-Position: refs/heads/master@{#410206}

TBR=thakis@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=635108

Review-Url: https://codereview.chromium.org/2218313002
Cr-Original-Commit-Position: refs/heads/master@{#410247}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d1d17ef355294fe1ad2f624711869003a3ded893