Fix build_clang_tools_extra.py on Windows.
The script fails with the following error on Windows when using the
--fetch flag:

Traceback (most recent call last):
  File "tools/clang/scripts/build_clang_tools_extra.py", line 97, in <module>
    sys.exit(main())
  File "tools/clang/scripts/build_clang_tools_extra.py", line 90, in main
    FetchLLVM(GetCheckoutDir(args.OUT_DIR), args.revision)
  File "tools/clang/scripts/build_clang_tools_extra.py", line 54, in FetchLLVM
    subprocess.check_call(args, cwd=checkout_dir)
  File "C:\python_27_amd64\files\lib\subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\python_27_amd64\files\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\python_27_amd64\files\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\python_27_amd64\files\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

With these few changes the scripts works fine on Windows.

This also switch this script to using GN instead of cmake.

Change-Id: I2af10fd0d03d4d18394b792e1b7780f2084bfa9a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1968071
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Sébastien Marchand <sebmarchand@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#726680}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 51f7506a2c5bd6ac0ca1ae7cb8d9e9fd56aa05a7